spring:
  profiles:
    active: local

  application:
    name: string

---

spring:
  security:
    user:
      password: 1

  datasource:
    url: jdbc:postgresql://localhost:5432/string
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  p6spy:
    enable-logging: true
    multiline: true
    logging: slf4j
    tracing:
      include-parameter-values: true

  jpa:
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true