spring:
  profiles:
    active: local

  application:
    name: string

---

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/string
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true