spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/string
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
